import type { CSSProperties } from "react";
import type { PipelineReviewShortlistSummary } from "./pipeline-review-types";

type PipelineShortlistProps = {
	shortlist: PipelineReviewShortlistSummary;
};

const sectionStyle: CSSProperties = {
	display: "grid",
	gap: "var(--jh-space-3)",
};

const headerStyle: CSSProperties = {
	fontFamily: "var(--jh-font-heading)",
	fontSize: "var(--jh-text-h4-size)",
	fontWeight: "var(--jh-text-h4-weight)" as never,
	marginBottom: 0,
	marginTop: 0,
};

const cardGridStyle: CSSProperties = {
	display: "grid",
	gap: "var(--jh-space-2)",
	gridTemplateColumns: "repeat(auto-fit, minmax(10rem, 1fr))",
};

const cardStyle: CSSProperties = {
	background: "var(--jh-color-pipeline-card-bg)",
	border: "1px solid var(--jh-color-pipeline-card-border)",
	borderRadius: "var(--jh-radius-md)",
	padding: "var(--jh-space-3)",
};

const cardLabelStyle: CSSProperties = {
	color: "var(--jh-color-text-muted)",
	fontSize: "var(--jh-text-caption-size)",
	margin: 0,
};

const cardValueStyle: CSSProperties = {
	fontWeight: "var(--jh-font-weight-semibold)" as never,
	margin: 0,
};

const guidanceStyle: CSSProperties = {
	background: "var(--jh-color-pipeline-guidance-bg)",
	border: "1px solid var(--jh-color-pipeline-guidance-border)",
	borderRadius: "var(--jh-radius-md)",
	padding: "var(--jh-space-3)",
};

const topRoleCardStyle: CSSProperties = {
	background: "var(--jh-color-pipeline-card-bg)",
	border: "1px solid var(--jh-color-pipeline-card-border)",
	borderRadius: "var(--jh-radius-md)",
	display: "grid",
	gap: "var(--jh-space-1)",
	padding: "var(--jh-space-3)",
};

const bucketChipStyle: CSSProperties = {
	background: "var(--jh-color-badge-info-bg)",
	borderRadius: "var(--jh-radius-pill)",
	color: "var(--jh-color-badge-info-fg)",
	fontSize: "var(--jh-text-label-sm-size)",
	fontWeight: "var(--jh-font-weight-bold)" as never,
	lineHeight: 1,
	padding: "2px 8px",
};

export function PipelineShortlist({ shortlist }: PipelineShortlistProps) {
	if (!shortlist.available) {
		return null;
	}

	return (
		<section style={sectionStyle}>
			<header>
				<h3 style={headerStyle}>Shortlist overview</h3>
				<p
					style={{
						color: "var(--jh-color-text-muted)",
						fontSize: "var(--jh-text-body-sm-size)",
						margin: 0,
					}}
				>
					{shortlist.message}
				</p>
			</header>

			<div style={cardGridStyle}>
				<article style={cardStyle}>
					<p style={cardLabelStyle}>Last refreshed</p>
					<p style={cardValueStyle}>{shortlist.lastRefreshed ?? "Unknown"}</p>
				</article>
				<article style={cardStyle}>
					<p style={cardLabelStyle}>Generated by</p>
					<p style={cardValueStyle}>{shortlist.generatedBy ?? "Unknown"}</p>
				</article>
				<article style={cardStyle}>
					<p style={cardLabelStyle}>Strongest fit</p>
					<p style={cardValueStyle}>
						{shortlist.bucketCounts.strongestFit ?? 0}
					</p>
				</article>
				<article style={cardStyle}>
					<p style={cardLabelStyle}>Possible fit</p>
					<p style={cardValueStyle}>
						{shortlist.bucketCounts.possibleFit ?? 0}
					</p>
				</article>
				<article style={cardStyle}>
					<p style={cardLabelStyle}>Adjacent or noisy</p>
					<p style={cardValueStyle}>
						{shortlist.bucketCounts.adjacentOrNoisy ?? 0}
					</p>
				</article>
			</div>

			{shortlist.campaignGuidance ? (
				<section style={guidanceStyle}>
					<strong>Campaign guidance</strong>
					<p style={{ marginBottom: 0, marginTop: "var(--jh-space-1)" }}>
						{shortlist.campaignGuidance}
					</p>
				</section>
			) : null}

			{shortlist.topRoles.length > 0 ? (
				<div style={{ display: "grid", gap: "var(--jh-space-2)" }}>
					{shortlist.topRoles.slice(0, 5).map((entry) => (
						<article
							key={`${entry.url}:${entry.role}`}
							style={topRoleCardStyle}
						>
							<div
								style={{
									alignItems: "center",
									display: "flex",
									flexWrap: "wrap",
									gap: "var(--jh-space-2)",
									justifyContent: "space-between",
								}}
							>
								<strong>{entry.role}</strong>
								<span style={bucketChipStyle}>{entry.bucketLabel}</span>
							</div>
							<span style={{ color: "var(--jh-color-text-secondary)" }}>
								{entry.company ?? "Unknown company"}
							</span>
							{entry.reasonSummary ? (
								<span style={{ color: "var(--jh-color-text-muted)" }}>
									{entry.reasonSummary}
								</span>
							) : null}
						</article>
					))}
				</div>
			) : null}
		</section>
	);
}
